/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vaccinemain;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author brend
 */
public class PeopleFunctionPage extends javax.swing.JFrame {
    
    public static String FullName;
    /**
     * Creates new form PeopleFunctionPage
     */
    public PeopleFunctionPage(String u) {
        
        initComponents();
        FullName = u;
    }
    
    public PeopleFunctionPage(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFunctions = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblWelcomeUser = new javax.swing.JLabel();
        btnBookAppointment = new javax.swing.JButton();
        btnViewAppointment = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnViewCentre = new javax.swing.JButton();
        btnModifyDetails = new javax.swing.JButton();
        btnViewVaccinationType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(642, 420));

        jPanel2.setBackground(new java.awt.Color(31, 187, 166));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 115));

        lblFunctions.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblFunctions.setForeground(new java.awt.Color(255, 255, 255));
        lblFunctions.setText("Function");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFunctions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFunctions)
                    .addComponent(jLabel1))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        btnLogOut.setBackground(new java.awt.Color(255, 150, 0));
        btnLogOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblWelcomeUser.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        lblWelcomeUser.setForeground(new java.awt.Color(0, 102, 102));
        lblWelcomeUser.setText("WELCOME USER");

        btnBookAppointment.setBackground(new java.awt.Color(249, 190, 63));
        btnBookAppointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBookAppointment.setForeground(new java.awt.Color(255, 255, 255));
        btnBookAppointment.setText("Book Vaccination Appointment");
        btnBookAppointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppointmentActionPerformed(evt);
            }
        });

        btnViewAppointment.setBackground(new java.awt.Color(249, 190, 63));
        btnViewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewAppointment.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAppointment.setText("View Own Appointment");
        btnViewAppointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnViewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAppointmentActionPerformed(evt);
            }
        });

        btnViewDetails.setBackground(new java.awt.Color(249, 190, 63));
        btnViewDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("View personal details");
        btnViewDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnViewCentre.setBackground(new java.awt.Color(249, 190, 63));
        btnViewCentre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewCentre.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCentre.setText("View Centre");
        btnViewCentre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnViewCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCentreActionPerformed(evt);
            }
        });

        btnModifyDetails.setBackground(new java.awt.Color(249, 190, 63));
        btnModifyDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModifyDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyDetails.setText("ModifyPersonal Details");
        btnModifyDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnModifyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyDetailsActionPerformed(evt);
            }
        });

        btnViewVaccinationType.setBackground(new java.awt.Color(249, 190, 63));
        btnViewVaccinationType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewVaccinationType.setForeground(new java.awt.Color(255, 255, 255));
        btnViewVaccinationType.setText("View Vaccination Type");
        btnViewVaccinationType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 150, 0), 3));
        btnViewVaccinationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVaccinationTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblWelcomeUser))
                    .addComponent(btnModifyDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBookAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewVaccinationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addGap(4, 4, 4)
                .addComponent(lblWelcomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewVaccinationType, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnBookAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnModifyDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyDetailsActionPerformed
        this.setVisible(false);
        ModifyOwnDetailsPage mo = new ModifyOwnDetailsPage(FullName);
        mo.show();
    }//GEN-LAST:event_btnModifyDetailsActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        this.setVisible(false);
        ViewOwnDetailsPage vodp = new ViewOwnDetailsPage(FullName);
        vodp.show();
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppointmentActionPerformed
              
        try
        {
            int flag = 1;
            BufferedReader myfile = new BufferedReader(new FileReader("Appointmentdata.txt"));

            String [] lineArr;
            String line;
            
            while((line = myfile.readLine())!=null)
            {
                lineArr = line.split(" , ");
                if((lineArr[0].equals(FullName)))   //if first column equals to FullNamee
                {
                    flag = 1;       
                    break;
                }
                else
                {
                    flag = 0;
                }
                        
            }
            
            if (flag == 0)  //None appointment at the moment
            {
                this.setVisible(false);
                BookAppointmentPage ba = new BookAppointmentPage(FullName);
                ba.setVisible(true);
            }
            else    //Since only one appointment is allowed
            {
                JOptionPane.showMessageDialog(null, "Your appointment record exists");
            }
            myfile.close();
            
   
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBookAppointmentActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.setVisible(false);
        LoginPage lp = new LoginPage();
        lp.show();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAppointmentActionPerformed
        this.setVisible(false);
        ViewOwnAppointmentPage vo = new ViewOwnAppointmentPage(FullName);
        vo.show();
    }//GEN-LAST:event_btnViewAppointmentActionPerformed

    private void btnViewCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCentreActionPerformed
        this.setVisible(false);
        PeopleSearchView psv = new PeopleSearchView(FullName);
        psv.setVisible(true);
    }//GEN-LAST:event_btnViewCentreActionPerformed

    private void btnViewVaccinationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVaccinationTypeActionPerformed
        this.setVisible(false);
        PeopleVaccine pv = new PeopleVaccine(FullName);
        pv.setVisible(true);
    }//GEN-LAST:event_btnViewVaccinationTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleFunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleFunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleFunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleFunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleFunctionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAppointment;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModifyDetails;
    private javax.swing.JButton btnViewAppointment;
    private javax.swing.JButton btnViewCentre;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewVaccinationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFunctions;
    private javax.swing.JLabel lblWelcomeUser;
    // End of variables declaration//GEN-END:variables
}
